# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required

language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.4"

addons:
  apt:
    sources:
      - pgavin-ghdl
    packages:
      - iverilog
      - ghdl

install:
  - pip install .

env:
  - CI_TARGET=core
  - CI_TARGET=icarus
  - CI_TARGET=ghdl
  - CI_TARGET=bugs
  - CI_TARGET=numeric

script: ./scripts/ci.sh

notifications:
  email: false
