-- File: issue_133.vhd
-- Generated by MyHDL 1.0dev
-- Date: Thu Dec 17 10:48:29 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package pck_issue_133 is

attribute enum_encoding: string;


end package pck_issue_133;

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use IEEE.standard_additions.all;
use IEEE.numeric_std_additions.all;
use std.textio.all;

use work.pck_myhdl_10.all;

use work.pck_issue_133.all;

entity issue_133 is
end entity issue_133;


architecture MyHDL of issue_133 is

    signal large_signal: unsigned(255 downto 0);
    signal z: std_logic;



    
begin

    large_signal <= "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011100000100100010000110000011111001000110000000";


    
    ISSUE_133_CHECK: process is
        variable print: line;
    begin
        z <= large_signal(10);
        wait for 10 * 1 ns;
        write(print, large_signal(integer(31-1) downto 0));
        writeline(output, print);
        write(print, large_signal(integer(62-1) downto 31));
        writeline(output, print);
        write(print, large_signal(integer(93-1) downto 62));
        writeline(output, print);
        wait;
    end process ISSUE_133_CHECK;
    
    
end architecture MyHDL;


